// Generated by CoffeeScript 1.7.1
var arc, changeSlice, data1, data2, slice, svg, tweenFunc;

svg = d3.select("svg").attr("height", "1000").attr("width", "1000").append("g").attr("transform", "translate(200,200)");

data1 = [
  {
    innerRadius: 100,
    outerRadius: 130,
    startAngle: 0,
    endAngle: 3
  }
];

data2 = [
  {
    innerRadius: 100,
    outerRadius: 130,
    startAngle: 0,
    endAngle: 5
  }
];

arc = d3.svg.arc();

tweenFunc = function(d) {
  var interpolate, startData;
  startData = {
    innerRadius: d.innerRadius,
    outerRadius: d.outerRadius,
    endAngle: 0,
    startAngle: 0
  };
  interpolate = d3.interpolate(startData, d);
  return function(t) {
    return arc(interpolate(t));
  };
};

slice = svg.append("path").datum(data2[0]).transition().duration(1000).attrTween("d", tweenFunc);

slice.style("fill", "red");

changeSlice = function() {
  return slice.datum(data2[0]).transition().duration(1000).attrTween("d", function(d) {
    var interpolate;
    this._current = this._current || d;
    interpolate = d3.interpolate(this._current, d);
    this._current = interpolate(0);
    return function(t) {
      return arc(interpolate(t));
    };
  });
};
