// Generated by CoffeeScript 1.7.1
var PieGraph;

PieGraph = {
  centerR: {
    "in": 0,
    out: 90
  },
  objectiveR: {
    "in": 90,
    out: 100
  },
  historyR: {
    "in": 100,
    out: 120
  },
  mediaR: {
    "in": 120,
    out: 140
  },
  init: function() {
    var data, pieGraph;
    pieGraph = d3.select(".pieGraph").append("g").attr("transform", "translate(500,1600)");
    data = {
      "subjective": 0.57,
      "objective": 0.43,
      "history": 0.7,
      "media": 0.752
    };
    this.createSection(pieGraph, "objective", data);
    this.createSection(pieGraph, "history", data);
    this.createSection(pieGraph, "media", data);
    return this.createSection(pieGraph, "center");
  },
  createDatum: function(name, endAngle) {
    return {
      innerRadius: PieGraph["" + name + "R"]["in"],
      outerRadius: PieGraph["" + name + "R"].out,
      startAngle: 0,
      endAngle: endAngle
    };
  },
  createSection: function(group, name, data) {
    var arc;
    arc = d3.svg.arc();
    group.append("path").datum(this.createDatum(name, 2 * Math.PI)).attr("d", arc).attr("class", "" + name + " back");
    if (data != null) {
      return group.append("path").datum(this.createDatum(name, data[name] * 2 * Math.PI)).attr("d", arc).attr("class", "" + name + " fore");
    }
  }
};
