// Generated by CoffeeScript 1.7.1
var SubGraph;

SubGraph = {
  minYear: -1,
  maxYear: -1,
  radius: 5,
  x: null,
  y: null,
  rootG: null,
  init: function() {
    this.minYear = d3.min(years, function(d) {
      return d.no;
    });
    this.maxYear = d3.max(years, function(d) {
      return d.no;
    });
    this.rootG = d3.select(".subGraph");
    this.x = d3.scale.linear().domain([0, 1]).range([ColumnX.pol, ColumnX.food]);
    return this.y = d3.scale.linear().domain([this.minYear, this.maxYear]).range([barWidth / 2, barWidth / 2 + barWidth * (this.maxYear - this.minYear)]);
  },
  draw: function() {
    WordTable.clear();
    drawYearLines(axisCanvas, overlayCanvas, {
      pol: 0,
      his: 0,
      food: 0
    });
    this.drawLine("food");
    this.drawLine("his");
    this.drawLine("pol");
    return this.drawLine("news");
  },
  drawLine: function(name, className, acc) {
    var data, group, line;
    if (className == null) {
      className = name;
    }
    if (acc == null) {
      acc = function(d) {
        return {
          value: d[name].obj,
          no: d.no
        };
      };
    }
    data = [];
    years.forEach(function(d) {
      if (name === "news" || d[name].kw.length !== 0) {
        return data.push(acc(d));
      }
    });
    group = SubGraph.rootG.append("g").attr("class", className);
    line = d3.svg.line().x(function(d) {
      return SubGraph.x(d.value);
    }).y(function(d) {
      return SubGraph.y(d.no);
    });
    group.append("path").datum(data).attr("d", line);
    return group.selectAll(".dot").data(data).enter().append("circle").attr("r", SubGraph.radius).attr("cx", function(d) {
      return SubGraph.x(d.value);
    }).attr("cy", function(d) {
      return SubGraph.y(d.no);
    });
  }
};
