// Generated by CoffeeScript 1.7.1
var WordCloud;

WordCloud = {
  targetSVG: null,
  totalWidth: 500,
  totalHeight: 300,
  margin: {
    top: 20,
    right: 10,
    left: 10,
    bottom: 20
  },
  svgWidth: 0,
  svgHeight: 0,
  init: function() {
    this.svgWidth = this.totalWidth - this.margin.left - this.margin.right;
    this.svgHeight = this.totalHeight - this.margin.top - this.margin.bottom;
    return d3.selectAll(".wordCloudSVG").attr("height", this.totalHeight).attr("width", this.totalWidth).append("g").attr("transform", "translate(" + (this.margin.left + this.svgWidth / 2) + "," + (this.margin.top + this.svgHeight / 2) + ")");
  },
  draw: function(words) {
    return WordCloud.targetSVG.selectAll("text").data(words).enter().append("text").attr("class", "wordCloudText").style("font-size", function(d) {
      return "" + d.size + "px";
    }).attr("transform", function(d) {
      return "translate(" + d.x + "," + d.y + ")";
    }).text(function(d) {
      return d.text;
    });
  },
  drawWordCloud: function(group, keywords, width, height) {
    var wordsToDraw;
    if (group != null) {
      this.targetSVG = group;
    } else {
      console.log("Error: group == null");
      return;
    }
    this.targetSVG.selectAll("text").remove();
    if (keywords.length > 0) {
      wordsToDraw = keywords.map(function(d) {
        return {
          text: d.w,
          size: 15 + 5 * d.f
        };
      });
    } else {
      wordsToDraw = [
        {
          text: "No keywords",
          size: 20
        }
      ];
    }
    return d3.layout.cloud().size([width, height]).words(wordsToDraw).padding(5).rotate(0).font("PT Sans").fontSize(function(d) {
      return d.size;
    }).on("end", this.draw).start();
  },
  drawKeywords: function(name, keywords) {
    var target;
    target = d3.select("#" + name + "SVG").select("g").attr("class", name);
    return this.drawWordCloud(target, keywords, this.svgWidth, this.svgHeight);
  }
};
